### ISSUE TITLE
Self hosting

### ISSUE THREAD

**Issue by smartboyathome** [FourthByteLabs/giganotes-desktop#3]
Stumbled across your app because I was looking for something similar to move on from my current wiki setup. Are there any plans to open source the backend of GigaNotes and allow for self hosting, for those so inclined?

**Comment by fourth-byte** [comment]
Hello, @smartboyathome, the Giganotes backend is a commercial product and we do not have any plans t open source it. Please let us know if you want to purchase a license and we will provide you the installer for server side together with documentation. You can do it by filling a form on our [GigaNotes](https://giganotes.com) website.
